# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GroupChannelMemberListRequest(BaseModel):
    """
    GroupChannelMemberListRequest
    """ # noqa: E501
    channel_id: StrictStr = Field(description="Group channel ID.", alias="channelId")
    member_role: Optional[StrictInt] = Field(default=None, description="Member role filter. `0` all members, `1` regular members, `2` admins, `3` owner.", alias="memberRole")
    page_token: Optional[StrictStr] = Field(default=None, description="Pagination token returned by the previous request. Omit it for the first page.", alias="pageToken")
    page_size: Optional[StrictInt] = Field(default=None, description="Number of members to return per page. The official default is 50 and the maximum is 100.", alias="pageSize")
    order: Optional[StrictInt] = Field(default=None, description="Sort order by join time. `0` ascending and `1` descending.")
    __properties: ClassVar[List[str]] = ["channelId", "memberRole", "pageToken", "pageSize", "order"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupChannelMemberListRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupChannelMemberListRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "channelId": obj.get("channelId"),
            "memberRole": obj.get("memberRole"),
            "pageToken": obj.get("pageToken"),
            "pageSize": obj.get("pageSize"),
            "order": obj.get("order")
        })
        return _obj


