# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GroupChannelProfileUpdateRequest(BaseModel):
    """
    GroupChannelProfileUpdateRequest
    """ # noqa: E501
    channel_id: StrictStr = Field(description="Legacy `groupId`.", alias="channelId")
    group_profile: Optional[Dict[str, Any]] = Field(default=None, description="Group basic profile object defined by the source API.", alias="groupProfile")
    permissions: Optional[Dict[str, Any]] = Field(default=None, description="Group permission object defined by the source API.")
    group_ext_profile: Optional[Dict[str, StrictStr]] = Field(default=None, description="Group extra profile object. Keys should use the `ext_` prefix and support up to 10 entries.", alias="groupExtProfile")
    __properties: ClassVar[List[str]] = ["channelId", "groupProfile", "permissions", "groupExtProfile"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupChannelProfileUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupChannelProfileUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "channelId": obj.get("channelId"),
            "groupProfile": obj.get("groupProfile"),
            "permissions": obj.get("permissions"),
            "groupExtProfile": obj.get("groupExtProfile")
        })
        return _obj


