# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ncsdk.models.stream_message_content import StreamMessageContent
from typing import Optional, Set
from typing_extensions import Self

class GroupChannelStreamMessageSendRequest(BaseModel):
    """
    GroupChannelStreamMessageSendRequest
    """ # noqa: E501
    from_user_id: StrictStr = Field(description="Sender user ID.", alias="fromUserId")
    to_channel_id: StrictStr = Field(description="Target group channel ID.", alias="toChannelId")
    message_type: StrictStr = Field(description="Message type. Fixed value `RC:StreamMsg` for stream messages.", alias="messageType")
    content: StreamMessageContent
    to_user_ids: Optional[List[StrictStr]] = Field(default=None, description="Recipient member user IDs for a targeted group message. Up to 10 users.", alias="toUserIds")
    is_echo_to_sender: Optional[StrictInt] = Field(default=None, description="Whether to sync the message to the sender's client while the sender is online. `1` enables sync and `0` disables it.", alias="isEchoToSender")
    should_persist: Optional[StrictInt] = Field(default=None, description="Whether to store the message in cloud message history. `0` means do not store and `1` means store.", alias="shouldPersist")
    has_mention: Optional[StrictInt] = Field(default=None, description="Whether this is an @mention message. Set to `1` when `content` contains `mentionedInfo`.", alias="hasMention")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Custom message metadata entries. Keys are limited to 32 characters and values to 4096 characters. Up to 100 key-value pairs.")
    disable_update_last_msg: Optional[StrictBool] = Field(default=None, description="Whether to keep this message from updating the channel's last-message preview.", alias="disableUpdateLastMsg")
    __properties: ClassVar[List[str]] = ["fromUserId", "toChannelId", "messageType", "content", "toUserIds", "isEchoToSender", "shouldPersist", "hasMention", "metadata", "disableUpdateLastMsg"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupChannelStreamMessageSendRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict['content'] = self.content.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupChannelStreamMessageSendRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fromUserId": obj.get("fromUserId"),
            "toChannelId": obj.get("toChannelId"),
            "messageType": obj.get("messageType"),
            "content": StreamMessageContent.from_dict(obj["content"]) if obj.get("content") is not None else None,
            "toUserIds": obj.get("toUserIds"),
            "isEchoToSender": obj.get("isEchoToSender"),
            "shouldPersist": obj.get("shouldPersist"),
            "hasMention": obj.get("hasMention"),
            "metadata": obj.get("metadata"),
            "disableUpdateLastMsg": obj.get("disableUpdateLastMsg")
        })
        return _obj


