# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ncsdk.models.message_metadata_list_item import MessageMetadataListItem
from typing import Optional, Set
from typing_extensions import Self

class MessageRecord(BaseModel):
    """
    MessageRecord
    """ # noqa: E501
    channel_id: Optional[StrictStr] = Field(default=None, description="Channel identifier of the stored message.", alias="channelId")
    subchannel_id: Optional[StrictStr] = Field(default=None, description="Community subchannel ID associated with the stored message, when applicable.", alias="subchannelId")
    from_user_id: Optional[StrictStr] = Field(default=None, description="Sender user ID of the stored message.", alias="fromUserId")
    message_id: Optional[StrictStr] = Field(default=None, description="Unique message ID.", alias="messageId")
    sent_at: Optional[StrictInt] = Field(default=None, description="Message send timestamp in milliseconds.", alias="sentAt")
    message_type: Optional[StrictStr] = Field(default=None, description="Message type of the stored message.", alias="messageType")
    channel_type: Optional[StrictInt] = Field(default=None, description="Channel type of the stored message.", alias="channelType")
    content: Optional[StrictStr] = Field(default=None, description="Raw message content payload as stored by the service.")
    has_metadata: Optional[StrictBool] = Field(default=None, description="Whether the message has metadata entries attached.", alias="hasMetadata")
    metadata: Optional[List[MessageMetadataListItem]] = Field(default=None, description="List of metadata entries (`CommunityHistoryMessage` uses `List<MetadataItem>`, not a map).")
    __properties: ClassVar[List[str]] = ["channelId", "subchannelId", "fromUserId", "messageId", "sentAt", "messageType", "channelType", "content", "hasMetadata", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in metadata (list)
        _items = []
        if self.metadata:
            for _item_metadata in self.metadata:
                if _item_metadata:
                    _items.append(_item_metadata.to_dict())
            _dict['metadata'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "channelId": obj.get("channelId"),
            "subchannelId": obj.get("subchannelId"),
            "fromUserId": obj.get("fromUserId"),
            "messageId": obj.get("messageId"),
            "sentAt": obj.get("sentAt"),
            "messageType": obj.get("messageType"),
            "channelType": obj.get("channelType"),
            "content": obj.get("content"),
            "hasMetadata": obj.get("hasMetadata"),
            "metadata": [MessageMetadataListItem.from_dict(_item) for _item in obj["metadata"]] if obj.get("metadata") is not None else None
        })
        return _obj


