# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class OpenChannelMessageSendRequest(BaseModel):
    """
    OpenChannelMessageSendRequest
    """ # noqa: E501
    from_user_id: StrictStr = Field(description="Sender user ID.", alias="fromUserId")
    to_channel_ids: List[StrictStr] = Field(description="Target open channel IDs. Multiple channels are allowed; the official documentation recommends up to 10 IDs per request.", alias="toChannelIds")
    message_type: StrictStr = Field(description="Message type. Supports built-in types and custom types registered in the client SDK. Custom types must not start with `RC:` and must not exceed 32 characters.", alias="messageType")
    content: StrictStr = Field(description="Message content payload serialized as a string. Built-in message types should use a JSON object string. Maximum size is 128 KB.")
    should_persist: Optional[StrictInt] = Field(default=None, description="Whether to store the message in open channel cloud history. `0` means do not store and `1` means store.", alias="shouldPersist")
    is_echo_to_sender: Optional[StrictInt] = Field(default=None, description="Whether to sync the sent message to the sender's client while online. `1` enables sync and `0` disables it.", alias="isEchoToSender")
    priority: Optional[StrictInt] = Field(default=None, description="Message priority. `0` standard, `1` allowlisted, `2` high priority, `3` low priority.")
    __properties: ClassVar[List[str]] = ["fromUserId", "toChannelIds", "messageType", "content", "shouldPersist", "isEchoToSender", "priority"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpenChannelMessageSendRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpenChannelMessageSendRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fromUserId": obj.get("fromUserId"),
            "toChannelIds": obj.get("toChannelIds"),
            "messageType": obj.get("messageType"),
            "content": obj.get("content"),
            "shouldPersist": obj.get("shouldPersist"),
            "isEchoToSender": obj.get("isEchoToSender"),
            "priority": obj.get("priority")
        })
        return _obj


