# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.open_channel_global_mute_list_add_request import OpenChannelGlobalMuteListAddRequest

class TestOpenChannelGlobalMuteListAddRequest(unittest.TestCase):
    """OpenChannelGlobalMuteListAddRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenChannelGlobalMuteListAddRequest:
        """Test OpenChannelGlobalMuteListAddRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenChannelGlobalMuteListAddRequest`
        """
        model = OpenChannelGlobalMuteListAddRequest()
        if include_optional:
            return OpenChannelGlobalMuteListAddRequest(
                participant_ids = [
                    ''
                    ],
                duration_minutes = 56,
                extra = '',
                need_notify = True
            )
        else:
            return OpenChannelGlobalMuteListAddRequest(
                participant_ids = [
                    ''
                    ],
                duration_minutes = 56,
        )
        """

    def testOpenChannelGlobalMuteListAddRequest(self):
        """Test OpenChannelGlobalMuteListAddRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
