# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.group_channel_member_favorites_list_response import GroupChannelMemberFavoritesListResponse

class TestGroupChannelMemberFavoritesListResponse(unittest.TestCase):
    """GroupChannelMemberFavoritesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupChannelMemberFavoritesListResponse:
        """Test GroupChannelMemberFavoritesListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupChannelMemberFavoritesListResponse`
        """
        model = GroupChannelMemberFavoritesListResponse()
        if include_optional:
            return GroupChannelMemberFavoritesListResponse(
                code = 56,
                result = ncsdk.models.group_channel_member_favorites_list_response_result.GroupChannelMemberFavoritesListResponse_result(
                    user_id = '', 
                    channel_id = '', 
                    favorites = [
                        ncsdk.models.group_channel_favorite_item.GroupChannelFavoriteItem(
                            user_id = '', 
                            favorited_at = 56, )
                        ], )
            )
        else:
            return GroupChannelMemberFavoritesListResponse(
                code = 56,
        )
        """

    def testGroupChannelMemberFavoritesListResponse(self):
        """Test GroupChannelMemberFavoritesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
