# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.community_channel_mute_list_add_request import CommunityChannelMuteListAddRequest

class TestCommunityChannelMuteListAddRequest(unittest.TestCase):
    """CommunityChannelMuteListAddRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityChannelMuteListAddRequest:
        """Test CommunityChannelMuteListAddRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityChannelMuteListAddRequest`
        """
        model = CommunityChannelMuteListAddRequest()
        if include_optional:
            return CommunityChannelMuteListAddRequest(
                channel_id = '',
                subchannel_id = '',
                user_ids = [
                    ''
                    ]
            )
        else:
            return CommunityChannelMuteListAddRequest(
                channel_id = '',
                user_ids = [
                    ''
                    ],
        )
        """

    def testCommunityChannelMuteListAddRequest(self):
        """Test CommunityChannelMuteListAddRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
