# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.community_channel_subchannel_user_group_list_response import CommunityChannelSubchannelUserGroupListResponse

class TestCommunityChannelSubchannelUserGroupListResponse(unittest.TestCase):
    """CommunityChannelSubchannelUserGroupListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityChannelSubchannelUserGroupListResponse:
        """Test CommunityChannelSubchannelUserGroupListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityChannelSubchannelUserGroupListResponse`
        """
        model = CommunityChannelSubchannelUserGroupListResponse()
        if include_optional:
            return CommunityChannelSubchannelUserGroupListResponse(
                code = 56,
                result = ncsdk.models.community_channel_subchannel_user_group_list_response_result.CommunityChannelSubchannelUserGroupListResponse_result(
                    user_group_ids = [
                        ''
                        ], )
            )
        else:
            return CommunityChannelSubchannelUserGroupListResponse(
                code = 56,
        )
        """

    def testCommunityChannelSubchannelUserGroupListResponse(self):
        """Test CommunityChannelSubchannelUserGroupListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
