# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.community_channel_message_metadata_set_request import CommunityChannelMessageMetadataSetRequest

class TestCommunityChannelMessageMetadataSetRequest(unittest.TestCase):
    """CommunityChannelMessageMetadataSetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityChannelMessageMetadataSetRequest:
        """Test CommunityChannelMessageMetadataSetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityChannelMessageMetadataSetRequest`
        """
        model = CommunityChannelMessageMetadataSetRequest()
        if include_optional:
            return CommunityChannelMessageMetadataSetRequest(
                message_id = '',
                user_id = '',
                channel_id = '',
                subchannel_id = '',
                metadata = {
                    'key' : ''
                    }
            )
        else:
            return CommunityChannelMessageMetadataSetRequest(
                message_id = '',
                user_id = '',
                channel_id = '',
                metadata = {
                    'key' : ''
                    },
        )
        """

    def testCommunityChannelMessageMetadataSetRequest(self):
        """Test CommunityChannelMessageMetadataSetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
