# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.group_channel_user_mute_list_get_response import GroupChannelUserMuteListGetResponse

class TestGroupChannelUserMuteListGetResponse(unittest.TestCase):
    """GroupChannelUserMuteListGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupChannelUserMuteListGetResponse:
        """Test GroupChannelUserMuteListGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupChannelUserMuteListGetResponse`
        """
        model = GroupChannelUserMuteListGetResponse()
        if include_optional:
            return GroupChannelUserMuteListGetResponse(
                code = 56,
                result = ncsdk.models.group_channel_user_mute_list_get_response_result.GroupChannelUserMuteListGetResponse_result(
                    muted_members = [
                        ncsdk.models.group_channel_muted_member_item.GroupChannelMutedMemberItem(
                            user_id = '', 
                            muted_at = '', 
                            mute_expires_at = '', )
                        ], )
            )
        else:
            return GroupChannelUserMuteListGetResponse(
                code = 56,
        )
        """

    def testGroupChannelUserMuteListGetResponse(self):
        """Test GroupChannelUserMuteListGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
