# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.community_channel_mute_list_get_request import CommunityChannelMuteListGetRequest

class TestCommunityChannelMuteListGetRequest(unittest.TestCase):
    """CommunityChannelMuteListGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityChannelMuteListGetRequest:
        """Test CommunityChannelMuteListGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityChannelMuteListGetRequest`
        """
        model = CommunityChannelMuteListGetRequest()
        if include_optional:
            return CommunityChannelMuteListGetRequest(
                channel_id = '',
                subchannel_id = '',
                page = 56,
                page_size = 56
            )
        else:
            return CommunityChannelMuteListGetRequest(
                channel_id = '',
        )
        """

    def testCommunityChannelMuteListGetRequest(self):
        """Test CommunityChannelMuteListGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
