# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.api.community_channel_management_api import CommunityChannelManagementApi


class TestCommunityChannelManagementApi(unittest.TestCase):
    """CommunityChannelManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommunityChannelManagementApi()

    def tearDown(self) -> None:
        pass

    def test_add_community_channel_user_group_users(self) -> None:
        """Test case for add_community_channel_user_group_users

        Add community channel user group users
        """
        pass

    def test_add_community_channel_user_groups(self) -> None:
        """Test case for add_community_channel_user_groups

        Add community channel user groups
        """
        pass

    def test_add_private_subchannel_members(self) -> None:
        """Test case for add_private_subchannel_members

        Add private subchannel members
        """
        pass

    def test_bind_community_channel_user_group(self) -> None:
        """Test case for bind_community_channel_user_group

        Bind community channel user group
        """
        pass

    def test_check_community_channel_member_exist(self) -> None:
        """Test case for check_community_channel_member_exist

        Check community channel member exist
        """
        pass

    def test_create_community_channel(self) -> None:
        """Test case for create_community_channel

        Create community channel
        """
        pass

    def test_create_community_subchannel(self) -> None:
        """Test case for create_community_subchannel

        Create community subchannel
        """
        pass

    def test_delete_community_subchannel(self) -> None:
        """Test case for delete_community_subchannel

        Delete community subchannel
        """
        pass

    def test_dismiss_community_channel(self) -> None:
        """Test case for dismiss_community_channel

        Dismiss community channel
        """
        pass

    def test_join_community_channel(self) -> None:
        """Test case for join_community_channel

        Join community channel
        """
        pass

    def test_list_community_channel_history_messages(self) -> None:
        """Test case for list_community_channel_history_messages

        List community-channel history messages
        """
        pass

    def test_list_community_channel_subchannel_user_groups(self) -> None:
        """Test case for list_community_channel_subchannel_user_groups

        List community channel subchannel user groups
        """
        pass

    def test_list_community_channel_user_group_subchannels(self) -> None:
        """Test case for list_community_channel_user_group_subchannels

        List community channel user group subchannels
        """
        pass

    def test_list_community_channel_user_groups(self) -> None:
        """Test case for list_community_channel_user_groups

        List community channel user groups
        """
        pass

    def test_list_community_channel_user_user_groups(self) -> None:
        """Test case for list_community_channel_user_user_groups

        List community channel user user groups
        """
        pass

    def test_list_community_subchannels(self) -> None:
        """Test case for list_community_subchannels

        List community subchannels
        """
        pass

    def test_list_community_user_subchannels(self) -> None:
        """Test case for list_community_user_subchannels

        List community user subchannels
        """
        pass

    def test_list_private_subchannel_members(self) -> None:
        """Test case for list_private_subchannel_members

        List private subchannel members
        """
        pass

    def test_quit_community_channel(self) -> None:
        """Test case for quit_community_channel

        Leave community channel
        """
        pass

    def test_remove_community_channel_user_group_users(self) -> None:
        """Test case for remove_community_channel_user_group_users

        Remove community channel user group users
        """
        pass

    def test_remove_community_channel_user_groups(self) -> None:
        """Test case for remove_community_channel_user_groups

        Delete community channel user groups
        """
        pass

    def test_remove_private_subchannel_members(self) -> None:
        """Test case for remove_private_subchannel_members

        Remove private subchannel members
        """
        pass

    def test_unbind_community_channel_user_group(self) -> None:
        """Test case for unbind_community_channel_user_group

        Unbind community channel user group
        """
        pass

    def test_update_community_channel_info(self) -> None:
        """Test case for update_community_channel_info

        Update community channel info
        """
        pass

    def test_update_community_subchannel_type(self) -> None:
        """Test case for update_community_subchannel_type

        Update community subchannel type
        """
        pass


if __name__ == '__main__':
    unittest.main()
