# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.open_channel_metadata_batch_get_response import OpenChannelMetadataBatchGetResponse

class TestOpenChannelMetadataBatchGetResponse(unittest.TestCase):
    """OpenChannelMetadataBatchGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenChannelMetadataBatchGetResponse:
        """Test OpenChannelMetadataBatchGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenChannelMetadataBatchGetResponse`
        """
        model = OpenChannelMetadataBatchGetResponse()
        if include_optional:
            return OpenChannelMetadataBatchGetResponse(
                code = 56,
                result = ncsdk.models.open_channel_metadata_batch_get_response_result.OpenChannelMetadataBatchGetResponse_result(
                    metadata = [
                        ncsdk.models.open_channel_metadata_entry.OpenChannelMetadataEntry(
                            key = '', 
                            value = '', 
                            metadata_owner_id = '', 
                            should_auto_delete = 56, 
                            updated_at = 56, )
                        ], )
            )
        else:
            return OpenChannelMetadataBatchGetResponse(
                code = 56,
        )
        """

    def testOpenChannelMetadataBatchGetResponse(self):
        """Test OpenChannelMetadataBatchGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
