# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.friend_list_response import FriendListResponse

class TestFriendListResponse(unittest.TestCase):
    """FriendListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FriendListResponse:
        """Test FriendListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FriendListResponse`
        """
        model = FriendListResponse()
        if include_optional:
            return FriendListResponse(
                code = 56,
                result = {"pageToken":"pageToken","totalCount":6,"friends":[{"addedAt":1,"friendExtProfile":{"key":""},"name":"name","alias":"alias","userId":"userId"},{"addedAt":1,"friendExtProfile":{"key":""},"name":"name","alias":"alias","userId":"userId"}]}
            )
        else:
            return FriendListResponse(
                code = 56,
        )
        """

    def testFriendListResponse(self):
        """Test FriendListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
