# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.group_channel_kick_user_from_all_request import GroupChannelKickUserFromAllRequest

class TestGroupChannelKickUserFromAllRequest(unittest.TestCase):
    """GroupChannelKickUserFromAllRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupChannelKickUserFromAllRequest:
        """Test GroupChannelKickUserFromAllRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupChannelKickUserFromAllRequest`
        """
        model = GroupChannelKickUserFromAllRequest()
        if include_optional:
            return GroupChannelKickUserFromAllRequest(
                user_id = ''
            )
        else:
            return GroupChannelKickUserFromAllRequest(
                user_id = '',
        )
        """

    def testGroupChannelKickUserFromAllRequest(self):
        """Test GroupChannelKickUserFromAllRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
