# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.community_channel_message_send_request import CommunityChannelMessageSendRequest

class TestCommunityChannelMessageSendRequest(unittest.TestCase):
    """CommunityChannelMessageSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityChannelMessageSendRequest:
        """Test CommunityChannelMessageSendRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityChannelMessageSendRequest`
        """
        model = CommunityChannelMessageSendRequest()
        if include_optional:
            return CommunityChannelMessageSendRequest(
                from_user_id = '',
                to_channel_ids = [
                    ''
                    ],
                to_user_ids = [
                    ''
                    ],
                message_type = '',
                content = '',
                push_content = '',
                push_data = '',
                should_persist = 56,
                is_counted = 56,
                has_mention = 56,
                content_available = 56,
                push_ext = '',
                subchannel_id = '',
                has_metadata = True,
                metadata = { }
            )
        else:
            return CommunityChannelMessageSendRequest(
                from_user_id = '',
                to_channel_ids = [
                    ''
                    ],
                message_type = '',
                content = '',
        )
        """

    def testCommunityChannelMessageSendRequest(self):
        """Test CommunityChannelMessageSendRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
