# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.api.user_management_api import UserManagementApi


class TestUserManagementApi(unittest.TestCase):
    """UserManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserManagementApi()

    def tearDown(self) -> None:
        pass

    def test_ban_users(self) -> None:
        """Test case for ban_users

        Ban a user
        """
        pass

    def test_batch_get_user_tags(self) -> None:
        """Test case for batch_get_user_tags

        Get user tags
        """
        pass

    def test_batch_set_user_tags(self) -> None:
        """Test case for batch_set_user_tags

        Batch set user tags
        """
        pass

    def test_expire_access_token(self) -> None:
        """Test case for expire_access_token

        Expire an access token
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get user info
        """
        pass

    def test_get_user_connection_status(self) -> None:
        """Test case for get_user_connection_status

        Check user online status
        """
        pass

    def test_issue_access_token(self) -> None:
        """Test case for issue_access_token

        Register a user
        """
        pass

    def test_list_banned_users(self) -> None:
        """Test case for list_banned_users

        List banned users
        """
        pass

    def test_list_channel_type_mute(self) -> None:
        """Test case for list_channel_type_mute

        List muted direct channel users
        """
        pass

    def test_list_soft_deleted_users(self) -> None:
        """Test case for list_soft_deleted_users

        Query soft-deleted users
        """
        pass

    def test_restore_users(self) -> None:
        """Test case for restore_users

        Restore a user
        """
        pass

    def test_set_channel_type_mute(self) -> None:
        """Test case for set_channel_type_mute

        Mute a user in direct channels
        """
        pass

    def test_soft_delete_users(self) -> None:
        """Test case for soft_delete_users

        Soft-delete a user
        """
        pass

    def test_unban_users(self) -> None:
        """Test case for unban_users

        Unban a user
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        Update user info
        """
        pass


if __name__ == '__main__':
    unittest.main()
