# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.open_channel_banned_participant_item import OpenChannelBannedParticipantItem

class TestOpenChannelBannedParticipantItem(unittest.TestCase):
    """OpenChannelBannedParticipantItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenChannelBannedParticipantItem:
        """Test OpenChannelBannedParticipantItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenChannelBannedParticipantItem`
        """
        model = OpenChannelBannedParticipantItem()
        if include_optional:
            return OpenChannelBannedParticipantItem(
                participant_id = '',
                ban_expires_at = ''
            )
        else:
            return OpenChannelBannedParticipantItem(
        )
        """

    def testOpenChannelBannedParticipantItem(self):
        """Test OpenChannelBannedParticipantItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
