# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.channel_tag_list_response import ChannelTagListResponse

class TestChannelTagListResponse(unittest.TestCase):
    """ChannelTagListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelTagListResponse:
        """Test ChannelTagListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelTagListResponse`
        """
        model = ChannelTagListResponse()
        if include_optional:
            return ChannelTagListResponse(
                code = 56,
                result = ncsdk.models.channel_tag_list_response_result.ChannelTagListResponse_result(
                    tag_id = '', 
                    channels = [
                        ncsdk.models.channel_tag_target_item.ChannelTagTargetItem(
                            channel_id = '', 
                            channel_type = 56, )
                        ], )
            )
        else:
            return ChannelTagListResponse(
                code = 56,
        )
        """

    def testChannelTagListResponse(self):
        """Test ChannelTagListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
