# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.group_channel_transfer_owner_request import GroupChannelTransferOwnerRequest

class TestGroupChannelTransferOwnerRequest(unittest.TestCase):
    """GroupChannelTransferOwnerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupChannelTransferOwnerRequest:
        """Test GroupChannelTransferOwnerRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupChannelTransferOwnerRequest`
        """
        model = GroupChannelTransferOwnerRequest()
        if include_optional:
            return GroupChannelTransferOwnerRequest(
                channel_id = '',
                new_owner = '',
                should_leave = 56,
                should_delete_mute = 56,
                should_delete_allowed_senders_list = 56,
                should_delete_favorites = 56
            )
        else:
            return GroupChannelTransferOwnerRequest(
                channel_id = '',
                new_owner = '',
        )
        """

    def testGroupChannelTransferOwnerRequest(self):
        """Test GroupChannelTransferOwnerRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
