# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.api.message_management_api import MessageManagementApi


class TestMessageManagementApi(unittest.TestCase):
    """MessageManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageManagementApi()

    def tearDown(self) -> None:
        pass

    def test_broadcast_open_channel_message(self) -> None:
        """Test case for broadcast_open_channel_message

        Broadcast to all open channels
        """
        pass

    def test_delete_channel_message_history(self) -> None:
        """Test case for delete_channel_message_history

        Delete server-side channel message history
        """
        pass

    def test_delete_channel_type_message_metadata(self) -> None:
        """Test case for delete_channel_type_message_metadata

        Delete message metadata
        """
        pass

    def test_delete_community_channel_message_metadata(self) -> None:
        """Test case for delete_community_channel_message_metadata

        Delete community-channel message metadata keys
        """
        pass

    def test_delete_message(self) -> None:
        """Test case for delete_message

        Delete a message (recall)
        """
        pass

    def test_list_channel_type_message_metadata(self) -> None:
        """Test case for list_channel_type_message_metadata

        Get message metadata
        """
        pass

    def test_list_community_channel_message_metadata(self) -> None:
        """Test case for list_community_channel_message_metadata

        List community-channel message metadata
        """
        pass

    def test_send_community_channel_message(self) -> None:
        """Test case for send_community_channel_message

        Send a community channel message
        """
        pass

    def test_send_direct_channel_message(self) -> None:
        """Test case for send_direct_channel_message

        Send a direct message
        """
        pass

    def test_send_group_channel_message(self) -> None:
        """Test case for send_group_channel_message

        Send a group message
        """
        pass

    def test_send_open_channel_message(self) -> None:
        """Test case for send_open_channel_message

        Send an open channel message
        """
        pass

    def test_set_channel_type_message_metadata(self) -> None:
        """Test case for set_channel_type_message_metadata

        Set message metadata
        """
        pass

    def test_set_community_channel_message_metadata(self) -> None:
        """Test case for set_community_channel_message_metadata

        Set community-channel message metadata
        """
        pass

    def test_update_community_channel_message(self) -> None:
        """Test case for update_community_channel_message

        Update community-channel message
        """
        pass

    def test_update_direct_channel_message(self) -> None:
        """Test case for update_direct_channel_message

        Update direct-channel message
        """
        pass

    def test_update_group_channel_message(self) -> None:
        """Test case for update_group_channel_message

        Update group-channel message
        """
        pass


if __name__ == '__main__':
    unittest.main()
