# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.group_channel_member_batch_get_response import GroupChannelMemberBatchGetResponse

class TestGroupChannelMemberBatchGetResponse(unittest.TestCase):
    """GroupChannelMemberBatchGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupChannelMemberBatchGetResponse:
        """Test GroupChannelMemberBatchGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupChannelMemberBatchGetResponse`
        """
        model = GroupChannelMemberBatchGetResponse()
        if include_optional:
            return GroupChannelMemberBatchGetResponse(
                code = 56,
                result = ncsdk.models.group_channel_member_batch_get_response_result.GroupChannelMemberBatchGetResponse_result(
                    page_token = '', 
                    total_count = 56, 
                    members = [
                        ncsdk.models.group_channel_member_item.GroupChannelMemberItem(
                            user_id = '', 
                            role = 56, 
                            nickname = '', 
                            extra = '', 
                            joined_at = 56, )
                        ], )
            )
        else:
            return GroupChannelMemberBatchGetResponse(
                code = 56,
        )
        """

    def testGroupChannelMemberBatchGetResponse(self):
        """Test GroupChannelMemberBatchGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
