# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.open_channel_freeze_check_response import OpenChannelFreezeCheckResponse

class TestOpenChannelFreezeCheckResponse(unittest.TestCase):
    """OpenChannelFreezeCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenChannelFreezeCheckResponse:
        """Test OpenChannelFreezeCheckResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenChannelFreezeCheckResponse`
        """
        model = OpenChannelFreezeCheckResponse()
        if include_optional:
            return OpenChannelFreezeCheckResponse(
                code = 56,
                result = ncsdk.models.open_channel_freeze_check_response_result.OpenChannelFreezeCheckResponse_result(
                    status = 56, )
            )
        else:
            return OpenChannelFreezeCheckResponse(
                code = 56,
        )
        """

    def testOpenChannelFreezeCheckResponse(self):
        """Test OpenChannelFreezeCheckResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
