# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.api.user_profile_hosting_api import UserProfileHostingApi


class TestUserProfileHostingApi(unittest.TestCase):
    """UserProfileHostingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserProfileHostingApi()

    def tearDown(self) -> None:
        pass

    def test_batch_get_user_profiles(self) -> None:
        """Test case for batch_get_user_profiles

        Batch get user profiles
        """
        pass

    def test_delete_user_profiles(self) -> None:
        """Test case for delete_user_profiles

        Clear user profiles
        """
        pass

    def test_list_user_profiles(self) -> None:
        """Test case for list_user_profiles

        List user profiles
        """
        pass

    def test_set_user_profile(self) -> None:
        """Test case for set_user_profile

        Set user profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
