# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.community_subchannel_key_request import CommunitySubchannelKeyRequest

class TestCommunitySubchannelKeyRequest(unittest.TestCase):
    """CommunitySubchannelKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunitySubchannelKeyRequest:
        """Test CommunitySubchannelKeyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunitySubchannelKeyRequest`
        """
        model = CommunitySubchannelKeyRequest()
        if include_optional:
            return CommunitySubchannelKeyRequest(
                channel_id = '',
                subchannel_id = ''
            )
        else:
            return CommunitySubchannelKeyRequest(
                channel_id = '',
                subchannel_id = '',
        )
        """

    def testCommunitySubchannelKeyRequest(self):
        """Test CommunitySubchannelKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
