# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.access_token_issue_response import AccessTokenIssueResponse

class TestAccessTokenIssueResponse(unittest.TestCase):
    """AccessTokenIssueResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessTokenIssueResponse:
        """Test AccessTokenIssueResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessTokenIssueResponse`
        """
        model = AccessTokenIssueResponse()
        if include_optional:
            return AccessTokenIssueResponse(
                code = 56,
                result = {"accessToken":"accessToken","userId":"userId"}
            )
        else:
            return AccessTokenIssueResponse(
                code = 56,
        )
        """

    def testAccessTokenIssueResponse(self):
        """Test AccessTokenIssueResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
