# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.api.group_channel_moderation_api import GroupChannelModerationApi


class TestGroupChannelModerationApi(unittest.TestCase):
    """GroupChannelModerationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupChannelModerationApi()

    def tearDown(self) -> None:
        pass

    def test_add_group_channel_allowed_sender_list(self) -> None:
        """Test case for add_group_channel_allowed_sender_list

        Add to allowed senders list
        """
        pass

    def test_add_group_channel_freeze_list(self) -> None:
        """Test case for add_group_channel_freeze_list

        Freeze a group
        """
        pass

    def test_add_group_channel_user_mute_list(self) -> None:
        """Test case for add_group_channel_user_mute_list

        Mute a group member
        """
        pass

    def test_get_group_channel_allowed_sender_list(self) -> None:
        """Test case for get_group_channel_allowed_sender_list

        Query allowed senders list
        """
        pass

    def test_get_group_channel_freeze_list(self) -> None:
        """Test case for get_group_channel_freeze_list

        Query group freeze status
        """
        pass

    def test_get_group_channel_user_mute_list(self) -> None:
        """Test case for get_group_channel_user_mute_list

        List muted group members
        """
        pass

    def test_remove_group_channel_allowed_sender_list(self) -> None:
        """Test case for remove_group_channel_allowed_sender_list

        Remove from allowed senders list
        """
        pass

    def test_remove_group_channel_freeze_list(self) -> None:
        """Test case for remove_group_channel_freeze_list

        Unfreeze a group
        """
        pass

    def test_remove_group_channel_user_mute_list(self) -> None:
        """Test case for remove_group_channel_user_mute_list

        Unmute a group member
        """
        pass


if __name__ == '__main__':
    unittest.main()
