# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.channel_type_message_metadata_delete_request import ChannelTypeMessageMetadataDeleteRequest

class TestChannelTypeMessageMetadataDeleteRequest(unittest.TestCase):
    """ChannelTypeMessageMetadataDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelTypeMessageMetadataDeleteRequest:
        """Test ChannelTypeMessageMetadataDeleteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelTypeMessageMetadataDeleteRequest`
        """
        model = ChannelTypeMessageMetadataDeleteRequest()
        if include_optional:
            return ChannelTypeMessageMetadataDeleteRequest(
                message_id = '',
                user_id = '',
                channel_type = 56,
                channel_id = '',
                keys = [
                    ''
                    ],
                sync_to_sender = 56
            )
        else:
            return ChannelTypeMessageMetadataDeleteRequest(
                message_id = '',
                user_id = '',
                channel_type = 56,
                channel_id = '',
                keys = [
                    ''
                    ],
        )
        """

    def testChannelTypeMessageMetadataDeleteRequest(self):
        """Test ChannelTypeMessageMetadataDeleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
