# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.community_channel_allowed_sender_list_get_request import CommunityChannelAllowedSenderListGetRequest

class TestCommunityChannelAllowedSenderListGetRequest(unittest.TestCase):
    """CommunityChannelAllowedSenderListGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityChannelAllowedSenderListGetRequest:
        """Test CommunityChannelAllowedSenderListGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityChannelAllowedSenderListGetRequest`
        """
        model = CommunityChannelAllowedSenderListGetRequest()
        if include_optional:
            return CommunityChannelAllowedSenderListGetRequest(
                channel_id = '',
                subchannel_id = '',
                page = 56,
                page_size = 56
            )
        else:
            return CommunityChannelAllowedSenderListGetRequest(
                channel_id = '',
        )
        """

    def testCommunityChannelAllowedSenderListGetRequest(self):
        """Test CommunityChannelAllowedSenderListGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
