# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.channel_type_message_metadata_list_response import ChannelTypeMessageMetadataListResponse

class TestChannelTypeMessageMetadataListResponse(unittest.TestCase):
    """ChannelTypeMessageMetadataListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelTypeMessageMetadataListResponse:
        """Test ChannelTypeMessageMetadataListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelTypeMessageMetadataListResponse`
        """
        model = ChannelTypeMessageMetadataListResponse()
        if include_optional:
            return ChannelTypeMessageMetadataListResponse(
                code = 56,
                result = ncsdk.models.channel_type_message_metadata_list_response_result.ChannelTypeMessageMetadataListResponse_result(
                    metadata = [
                        ncsdk.models.message_metadata_list_item.MessageMetadataListItem(
                            key = '', 
                            value = '', 
                            updated_at = 56, )
                        ], )
            )
        else:
            return ChannelTypeMessageMetadataListResponse(
                code = 56,
        )
        """

    def testChannelTypeMessageMetadataListResponse(self):
        """Test ChannelTypeMessageMetadataListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
