# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.api.open_channel_participants_moderation_api import OpenChannelParticipantsModerationApi


class TestOpenChannelParticipantsModerationApi(unittest.TestCase):
    """OpenChannelParticipantsModerationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenChannelParticipantsModerationApi()

    def tearDown(self) -> None:
        pass

    def test_add_open_channel_freeze_list(self) -> None:
        """Test case for add_open_channel_freeze_list

        Freeze an open channel
        """
        pass

    def test_add_open_channel_global_mute_list(self) -> None:
        """Test case for add_open_channel_global_mute_list

        Mute a user globally
        """
        pass

    def test_add_open_channel_participant_allowed_sender_list(self) -> None:
        """Test case for add_open_channel_participant_allowed_sender_list

        Add to allowed senders list
        """
        pass

    def test_add_open_channel_participant_ban_list(self) -> None:
        """Test case for add_open_channel_participant_ban_list

        Ban a participant
        """
        pass

    def test_add_open_channel_participant_mute_list(self) -> None:
        """Test case for add_open_channel_participant_mute_list

        Mute a participant
        """
        pass

    def test_check_open_channel_freeze(self) -> None:
        """Test case for check_open_channel_freeze

        Check open channel freeze status
        """
        pass

    def test_check_open_channel_participants_exist(self) -> None:
        """Test case for check_open_channel_participants_exist

        Batch check participants
        """
        pass

    def test_get_open_channel_global_mute_list(self) -> None:
        """Test case for get_open_channel_global_mute_list

        List globally muted users
        """
        pass

    def test_get_open_channel_participant_allowed_sender_list(self) -> None:
        """Test case for get_open_channel_participant_allowed_sender_list

        Query allowed senders list
        """
        pass

    def test_get_open_channel_participant_ban_list(self) -> None:
        """Test case for get_open_channel_participant_ban_list

        List banned participants
        """
        pass

    def test_get_open_channel_participant_mute_list(self) -> None:
        """Test case for get_open_channel_participant_mute_list

        List muted participants
        """
        pass

    def test_list_frozen_open_channels(self) -> None:
        """Test case for list_frozen_open_channels

        List frozen open channels
        """
        pass

    def test_list_open_channel_participants(self) -> None:
        """Test case for list_open_channel_participants

        List participants
        """
        pass

    def test_remove_open_channel_freeze_list(self) -> None:
        """Test case for remove_open_channel_freeze_list

        Unfreeze an open channel
        """
        pass

    def test_remove_open_channel_global_mute_list(self) -> None:
        """Test case for remove_open_channel_global_mute_list

        Unmute a user globally
        """
        pass

    def test_remove_open_channel_participant_allowed_sender_list(self) -> None:
        """Test case for remove_open_channel_participant_allowed_sender_list

        Remove from allowed senders list
        """
        pass

    def test_remove_open_channel_participant_ban_list(self) -> None:
        """Test case for remove_open_channel_participant_ban_list

        Unban a participant
        """
        pass

    def test_remove_open_channel_participant_mute_list(self) -> None:
        """Test case for remove_open_channel_participant_mute_list

        Unmute a participant
        """
        pass


if __name__ == '__main__':
    unittest.main()
