# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.user_ban_list_response import UserBanListResponse

class TestUserBanListResponse(unittest.TestCase):
    """UserBanListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserBanListResponse:
        """Test UserBanListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserBanListResponse`
        """
        model = UserBanListResponse()
        if include_optional:
            return UserBanListResponse(
                code = 56,
                result = {"bannedUsers":[{"banExpiresAt":"banExpiresAt","userId":"userId"},{"banExpiresAt":"banExpiresAt","userId":"userId"}]}
            )
        else:
            return UserBanListResponse(
                code = 56,
        )
        """

    def testUserBanListResponse(self):
        """Test UserBanListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
