# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.group_channel_freeze_list_get_response import GroupChannelFreezeListGetResponse

class TestGroupChannelFreezeListGetResponse(unittest.TestCase):
    """GroupChannelFreezeListGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupChannelFreezeListGetResponse:
        """Test GroupChannelFreezeListGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupChannelFreezeListGetResponse`
        """
        model = GroupChannelFreezeListGetResponse()
        if include_optional:
            return GroupChannelFreezeListGetResponse(
                code = 56,
                result = ncsdk.models.group_channel_freeze_list_get_response_result.GroupChannelFreezeListGetResponse_result(
                    freeze_statuses = [
                        ncsdk.models.group_channel_freeze_status_item.GroupChannelFreezeStatusItem(
                            channel_id = '', 
                            status = 56, )
                        ], )
            )
        else:
            return GroupChannelFreezeListGetResponse(
                code = 56,
        )
        """

    def testGroupChannelFreezeListGetResponse(self):
        """Test GroupChannelFreezeListGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
