# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.user_update_request import UserUpdateRequest

class TestUserUpdateRequest(unittest.TestCase):
    """UserUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUpdateRequest:
        """Test UserUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUpdateRequest`
        """
        model = UserUpdateRequest()
        if include_optional:
            return UserUpdateRequest(
                user_id = '',
                name = '',
                avatar_url = ''
            )
        else:
            return UserUpdateRequest(
                user_id = '',
        )
        """

    def testUserUpdateRequest(self):
        """Test UserUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
