# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.group_channel_message_send_request import GroupChannelMessageSendRequest

class TestGroupChannelMessageSendRequest(unittest.TestCase):
    """GroupChannelMessageSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupChannelMessageSendRequest:
        """Test GroupChannelMessageSendRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupChannelMessageSendRequest`
        """
        model = GroupChannelMessageSendRequest()
        if include_optional:
            return GroupChannelMessageSendRequest(
                from_user_id = '',
                to_channel_ids = [
                    ''
                    ],
                to_user_ids = [
                    ''
                    ],
                message_type = '',
                content = '',
                push_content = '',
                push_data = '',
                is_echo_to_sender = 56,
                should_persist = 56,
                has_mention = 56,
                content_available = 56,
                has_metadata = True,
                metadata = { },
                disable_push = True,
                push_ext = '',
                disable_update_last_msg = True,
                need_read_receipt = 56
            )
        else:
            return GroupChannelMessageSendRequest(
                from_user_id = '',
                to_channel_ids = [
                    ''
                    ],
                message_type = '',
                content = '',
        )
        """

    def testGroupChannelMessageSendRequest(self):
        """Test GroupChannelMessageSendRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
