# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.open_channel_message_type_list_response import OpenChannelMessageTypeListResponse

class TestOpenChannelMessageTypeListResponse(unittest.TestCase):
    """OpenChannelMessageTypeListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenChannelMessageTypeListResponse:
        """Test OpenChannelMessageTypeListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenChannelMessageTypeListResponse`
        """
        model = OpenChannelMessageTypeListResponse()
        if include_optional:
            return OpenChannelMessageTypeListResponse(
                code = 56,
                result = ncsdk.models.open_channel_message_type_list_response_result.OpenChannelMessageTypeListResponse_result(
                    message_types = [
                        ''
                        ], )
            )
        else:
            return OpenChannelMessageTypeListResponse(
                code = 56,
        )
        """

    def testOpenChannelMessageTypeListResponse(self):
        """Test OpenChannelMessageTypeListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
