# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.message_record import MessageRecord

class TestMessageRecord(unittest.TestCase):
    """MessageRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageRecord:
        """Test MessageRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageRecord`
        """
        model = MessageRecord()
        if include_optional:
            return MessageRecord(
                channel_id = '',
                subchannel_id = '',
                from_user_id = '',
                message_id = '',
                sent_at = 56,
                message_type = '',
                channel_type = 56,
                content = '',
                has_metadata = True,
                metadata = [
                    ncsdk.models.message_metadata_list_item.MessageMetadataListItem(
                        key = '', 
                        value = '', 
                        updated_at = 56, )
                    ]
            )
        else:
            return MessageRecord(
        )
        """

    def testMessageRecord(self):
        """Test MessageRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
