# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.open_channel_freeze_list_update_request import OpenChannelFreezeListUpdateRequest

class TestOpenChannelFreezeListUpdateRequest(unittest.TestCase):
    """OpenChannelFreezeListUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenChannelFreezeListUpdateRequest:
        """Test OpenChannelFreezeListUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenChannelFreezeListUpdateRequest`
        """
        model = OpenChannelFreezeListUpdateRequest()
        if include_optional:
            return OpenChannelFreezeListUpdateRequest(
                channel_id = '',
                extra = '',
                need_notify = True
            )
        else:
            return OpenChannelFreezeListUpdateRequest(
                channel_id = '',
        )
        """

    def testOpenChannelFreezeListUpdateRequest(self):
        """Test OpenChannelFreezeListUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
