# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.api.open_channel_management_api import OpenChannelManagementApi


class TestOpenChannelManagementApi(unittest.TestCase):
    """OpenChannelManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenChannelManagementApi()

    def tearDown(self) -> None:
        pass

    def test_create_open_channel(self) -> None:
        """Test case for create_open_channel

        Create an open channel
        """
        pass

    def test_destroy_open_channels(self) -> None:
        """Test case for destroy_open_channels

        Destroy an open channel
        """
        pass

    def test_get_open_channel(self) -> None:
        """Test case for get_open_channel

        Get open channel info
        """
        pass

    def test_set_open_channel_destroy_type(self) -> None:
        """Test case for set_open_channel_destroy_type

        Set auto-destroy type
        """
        pass


if __name__ == '__main__':
    unittest.main()
