# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.friend_add_request import FriendAddRequest

class TestFriendAddRequest(unittest.TestCase):
    """FriendAddRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FriendAddRequest:
        """Test FriendAddRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FriendAddRequest`
        """
        model = FriendAddRequest()
        if include_optional:
            return FriendAddRequest(
                user_id = '',
                target_id = '',
                action = 56,
                extra = ''
            )
        else:
            return FriendAddRequest(
                user_id = '',
                target_id = '',
        )
        """

    def testFriendAddRequest(self):
        """Test FriendAddRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
