# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.profanity_word_batch_add_request import ProfanityWordBatchAddRequest

class TestProfanityWordBatchAddRequest(unittest.TestCase):
    """ProfanityWordBatchAddRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfanityWordBatchAddRequest:
        """Test ProfanityWordBatchAddRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfanityWordBatchAddRequest`
        """
        model = ProfanityWordBatchAddRequest()
        if include_optional:
            return ProfanityWordBatchAddRequest(
                words = [
                    ncsdk.models.profanity_word_item.ProfanityWordItem(
                        word = '', 
                        replacement = '', )
                    ]
            )
        else:
            return ProfanityWordBatchAddRequest(
                words = [
                    ncsdk.models.profanity_word_item.ProfanityWordItem(
                        word = '', 
                        replacement = '', )
                    ],
        )
        """

    def testProfanityWordBatchAddRequest(self):
        """Test ProfanityWordBatchAddRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
