# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.open_channel_metadata_batch_get_request import OpenChannelMetadataBatchGetRequest

class TestOpenChannelMetadataBatchGetRequest(unittest.TestCase):
    """OpenChannelMetadataBatchGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenChannelMetadataBatchGetRequest:
        """Test OpenChannelMetadataBatchGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenChannelMetadataBatchGetRequest`
        """
        model = OpenChannelMetadataBatchGetRequest()
        if include_optional:
            return OpenChannelMetadataBatchGetRequest(
                channel_id = '',
                metadata_keys = [
                    ''
                    ]
            )
        else:
            return OpenChannelMetadataBatchGetRequest(
                channel_id = '',
        )
        """

    def testOpenChannelMetadataBatchGetRequest(self):
        """Test OpenChannelMetadataBatchGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
