# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.group_channel_user_mute_list_add_request import GroupChannelUserMuteListAddRequest

class TestGroupChannelUserMuteListAddRequest(unittest.TestCase):
    """GroupChannelUserMuteListAddRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupChannelUserMuteListAddRequest:
        """Test GroupChannelUserMuteListAddRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupChannelUserMuteListAddRequest`
        """
        model = GroupChannelUserMuteListAddRequest()
        if include_optional:
            return GroupChannelUserMuteListAddRequest(
                channel_id = '',
                user_ids = [
                    ''
                    ],
                duration_minutes = 56
            )
        else:
            return GroupChannelUserMuteListAddRequest(
                user_ids = [
                    ''
                    ],
                duration_minutes = 56,
        )
        """

    def testGroupChannelUserMuteListAddRequest(self):
        """Test GroupChannelUserMuteListAddRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
