# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.community_channel_subchannel_user_group_list_request import CommunityChannelSubchannelUserGroupListRequest

class TestCommunityChannelSubchannelUserGroupListRequest(unittest.TestCase):
    """CommunityChannelSubchannelUserGroupListRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommunityChannelSubchannelUserGroupListRequest:
        """Test CommunityChannelSubchannelUserGroupListRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommunityChannelSubchannelUserGroupListRequest`
        """
        model = CommunityChannelSubchannelUserGroupListRequest()
        if include_optional:
            return CommunityChannelSubchannelUserGroupListRequest(
                channel_id = '',
                subchannel_id = '',
                page = 56,
                page_size = 56
            )
        else:
            return CommunityChannelSubchannelUserGroupListRequest(
                channel_id = '',
                subchannel_id = '',
        )
        """

    def testCommunityChannelSubchannelUserGroupListRequest(self):
        """Test CommunityChannelSubchannelUserGroupListRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
