# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.group_channel_member_batch_get_request import GroupChannelMemberBatchGetRequest

class TestGroupChannelMemberBatchGetRequest(unittest.TestCase):
    """GroupChannelMemberBatchGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupChannelMemberBatchGetRequest:
        """Test GroupChannelMemberBatchGetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupChannelMemberBatchGetRequest`
        """
        model = GroupChannelMemberBatchGetRequest()
        if include_optional:
            return GroupChannelMemberBatchGetRequest(
                channel_id = '',
                user_ids = [
                    ''
                    ]
            )
        else:
            return GroupChannelMemberBatchGetRequest(
                channel_id = '',
                user_ids = [
                    ''
                    ],
        )
        """

    def testGroupChannelMemberBatchGetRequest(self):
        """Test GroupChannelMemberBatchGetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
