# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.user_channel_tag_list_item import UserChannelTagListItem

class TestUserChannelTagListItem(unittest.TestCase):
    """UserChannelTagListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserChannelTagListItem:
        """Test UserChannelTagListItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserChannelTagListItem`
        """
        model = UserChannelTagListItem()
        if include_optional:
            return UserChannelTagListItem(
                tag_id = '',
                tag_name = '',
                created_at = 56
            )
        else:
            return UserChannelTagListItem(
        )
        """

    def testUserChannelTagListItem(self):
        """Test UserChannelTagListItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
