# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.direct_channel_stream_message_send_request import DirectChannelStreamMessageSendRequest

class TestDirectChannelStreamMessageSendRequest(unittest.TestCase):
    """DirectChannelStreamMessageSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DirectChannelStreamMessageSendRequest:
        """Test DirectChannelStreamMessageSendRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DirectChannelStreamMessageSendRequest`
        """
        model = DirectChannelStreamMessageSendRequest()
        if include_optional:
            return DirectChannelStreamMessageSendRequest(
                from_user_id = '',
                to_user_id = '',
                message_type = '',
                content = {"content":"Hello","seq":1,"complete":false},
                is_echo_to_sender = 56,
                should_persist = 56,
                metadata = {
                    'key' : ''
                    },
                disable_update_last_msg = True
            )
        else:
            return DirectChannelStreamMessageSendRequest(
                from_user_id = '',
                to_user_id = '',
                message_type = '',
                content = {"content":"Hello","seq":1,"complete":false},
        )
        """

    def testDirectChannelStreamMessageSendRequest(self):
        """Test DirectChannelStreamMessageSendRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
