# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.user_profile_list_item import UserProfileListItem

class TestUserProfileListItem(unittest.TestCase):
    """UserProfileListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserProfileListItem:
        """Test UserProfileListItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserProfileListItem`
        """
        model = UserProfileListItem()
        if include_optional:
            return UserProfileListItem(
                user_id = '',
                version = 56,
                user_profile = { },
                user_ext_profile = { }
            )
        else:
            return UserProfileListItem(
        )
        """

    def testUserProfileListItem(self):
        """Test UserProfileListItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
