# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ncsdk.models.system_channel_message_send_request import SystemChannelMessageSendRequest

class TestSystemChannelMessageSendRequest(unittest.TestCase):
    """SystemChannelMessageSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SystemChannelMessageSendRequest:
        """Test SystemChannelMessageSendRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SystemChannelMessageSendRequest`
        """
        model = SystemChannelMessageSendRequest()
        if include_optional:
            return SystemChannelMessageSendRequest(
                from_user_id = '',
                to_user_ids = [
                    ''
                    ],
                message_type = '',
                content = '',
                push_content = '',
                push_data = '',
                should_persist = 56,
                content_available = 56,
                disable_push = True,
                push_ext = '',
                disable_update_last_msg = True
            )
        else:
            return SystemChannelMessageSendRequest(
                from_user_id = '',
                to_user_ids = [
                    ''
                    ],
                message_type = '',
                content = '',
        )
        """

    def testSystemChannelMessageSendRequest(self):
        """Test SystemChannelMessageSendRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
