# coding: utf-8

"""
    Nexconn Server API

    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

    Contact: customercare@nexconn.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "nexconn-sdk-python"
VERSION = "0.1.1"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Nexconn Server API",
    author="Nexconn",
    author_email="customercare@nexconn.ai",
    url="https://github.com/NexconnAI-Dev/nexconn-server-sdk-python",
    keywords=["OpenAPI", "OpenAPI-Generator", "Nexconn Server API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description_content_type='text/markdown',
    long_description="""\
    OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
    """,  # noqa: E501
    package_data={"ncsdk": ["py.typed"]},
)